Mutation:
  type: object
  config:
    fields:
      addProduct:
        type: Product!
        resolve: "@=service('app.resolver.items').addProduct(args)"
        args:
          input:
            type: ProductInput!
      addCategory:
        type: Category!
        resolve: "@=service('app.resolver.categories').addCategory(args)"
        args:
          input:
            type: CategoryInput!