Query:
  type: object
  config:
    description: "Products ORM repository"
    fields:
      product:
        type: "Product"
        args:
          id:
            description: "Resolves using the product id."
            type: "String"
        resolve: "@=resolver('Product', [args])"
      category:
        type: "Category"
        args:
          id:
            description: "Resolves using the category id."
            type: "String"
        resolve: "@=resolver('Category', [args])"

